name: Run bandit

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        pip install nox
    - name: Run bandit
      run: |
        nox --sessions bandit