name: Deploy to pypi

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - name: Install dependencies
      run: |
        python setup.py sdist bdist_wheel
    - name: Build package
      run: |
        pip install wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
