name: Check sphinx building

on:
  push:
    branches: development
  pull_request:
    branches: development

jobs:
  sphinx_building:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install nox
    - name: Build with an old sphinx version
      run: nox --sessions test_sphinx_old_build
    - name: Build with latest sphinx version
      run: nox --sessions test_sphinx_build
